<?php 
   $mathjax=1;
   /*Check that this file is being accessed by the template*/
   if (!isset($in_template))
   {
   header( 'Location: /index.php/404');
   return;
   }
   $pagetitle="Configuration File Format Reference";
   ?>
<?php printTOC(); ?>
<p style="text-align:center; margin:15px; background-color:#FFD800; font-size:16pt; font-family:sans; line-height:40px;">
  <b>This reference is currently being written and is incomplete.</b>
</p>
<p>
  In this reference a complete description of the available output
  plugins of DynamO, and how to load them is presented.
</p>
<p>
  By default, DynamO loads the <a href="#misc-plugin">Misc output
  plugin</a> which collects a wide range of data. However, if there is
  any output which requires a large computational cost to collect,
  this must be enabled manually.
</p>
<h1>Loading Plugins</h1>
<p>
  Once you have chosen a plugin to load, you simply add it to the
  dynarun command line using the <i>-L</i> option. For example, to
  load the <a href="#intenergyhist-internal-energy-histogram">internal
  energy histogram plugin</a>, you would run
</p>
<?php codeblockstart(); ?>
dynarun config.xml -c 1000000 -L IntEnergyHist
<?php codeblockend("brush: shell;"); ?>
<p>
  And the <i>output.xml.bz2</i> file generated by this dynarun command
  will now contain a histogram of the internal energy. Many of the
  output plugins can take options and can be set using a colon after
  the plugin name, like so:
</p>
<?php codeblockstart(); ?>
dynarun config.xml -c 1000000 -L IntEnergyHist:BinWidth=0.1
<?php codeblockend("brush: shell;"); ?>
<p>
  If you need to specify multiple options, you must use a comma to
  delimit options:
</p>
<?php codeblockstart(); ?>
dynarun config.xml -c 1000000 -L MFT:BinWidth=0.5,Length=100
<?php codeblockend("brush: shell;"); ?>
<h1>Available Plugins</h1>
<p>
  In the following sections, the options and output of each output
  plugin are listed.
</p>
<h2>Misc Plugin</h2>
<p>
</p>
<h2>IntEnergyHist (Internal Energy Histogram)</h2>
<p>
  
</p>
<h2>MFT (Mean Free Time)</h2>
<p>
  
</p>
<h2>RadiusGyration</h2>
<p>

</p>
