<?php 
   $mathjax=1;
   /*Check that this file is being accessed by the template*/
   if (!isset($in_template))
   {
   header( 'Location: /index.php/404');
   return;
   }
   $pagetitle="Output Plugin/File Reference";
   ?>
<?php printTOC(); ?>
<p style="text-align:center; margin:15px; background-color:#FFD800; font-size:16pt; font-family:sans; line-height:40px;">
  <b>This reference is currently being written and is incomplete.</b>
</p>
<p>
  In this reference a complete description of the available output
  plugins of DynamO, and how to load them is presented.
</p>
<p>
  Output plugins are routines which can be activated in DynamO to
  collect measurements on the simulation <i>while it is
  running</i>. Although most static/structural properties can be
  measured from the configuration files, dynamical properties must be
  measured using output plugins. There are a wide range of properties
  which can be measured by DynamO, from transport properties
  (viscosity, mutual diffusion, thermal conductivity) to internal
  energy histograms.
</p>
<p>
  All data collected by active output plugins is written into a single
  XML file at the end of a simulation (<i>output.xml.bz2</i> by
  default).
</p>
<p>
  DynamO loads the <a href="#misc-plugin">Misc output plugin</a>
  automatically as it samples a wide range of properties of the system
  which are computationally inexpensive to collect; however, all other
  output plugins must be enabled manually. This is discussed in the
  following section:
</p>
<h1>Loading Plugins</h1>
<p>
  Once you have chosen a plugin to load, you simply add it to the
  dynarun command line using the <i>-L</i> option. For example, to
  load the <a href="#intenergyhist-internal-energy-histogram">internal
  energy histogram plugin</a>, you would run
</p>
<?php codeblockstart(); ?>
dynarun config.xml -c 1000000 -L IntEnergyHist
<?php codeblockend("brush: shell;"); ?>
<p>
  And the <i>output.xml.bz2</i> file generated by this dynarun command
  will now contain a histogram of the internal energy. Many of the
  output plugins can take options and can be set using a colon after
  the plugin name, like so:
</p>
<?php codeblockstart(); ?>
dynarun config.xml -c 1000000 -L IntEnergyHist:BinWidth=0.1
<?php codeblockend("brush: shell;"); ?>
<p>
  If you need to specify multiple options, you must use a comma to
  delimit options. For example, the <a href="#mft-mean-free-time">mean
  free time plugin</a> has two options which can be set like so:
</p>
<?php codeblockstart(); ?>
dynarun config.xml -c 1000000 -L MFT:BinWidth=0.5,Length=100
<?php codeblockend("brush: shell;"); ?>
<p>
  The options and the generated output of all available output plugins
  is detailed below.
</p>
<h1>Plugins</h1>
<p>
  In the following sections, the options and output of each output
  plugin are listed along with details on the calculation of the
  properties.
</p>
<h2>Misc Plugin</h2>
<p>
  The Misc plugin is loaded automatically and contains properties
  which are relatively cheap to collect. Fortunately, this includes
  the majority of the output which it is possible to collect with
  DynamO. The output tags of the Misc plugin and how they are
  collected are discussed in the following subsections.
</p>
<h3>Density</h3>
<p>
  This tag contains the number of particles divided by the volume of
  the primary image. In non-periodic systems, this value may not have
  any significance as the primary image is not related to the dynamics
  of the system. Complex boundary effects, such as walls reducing the
  accessible volume of the system, are not included in this
  calculation.
</p>
<p>
  <b>Example output</b>:
</p>
<?php codeblockstart();?>
<Misc>
  <Density val="0.5"/>
</Misc>
<?php codeblockend("brush: xml;"); ?>
<p>
  <b>Full Tag, Subtag, and Attribute List</b>:
</p>
<ul>
  <li>
    <b>val</b> <i>(attribute)</i>: The number density of the system
    ($N/V$).
  </li>
</ul>
<h3>Packing Fraction</h3>
<p>
  This tag contains the excluded volume of all particles divided by
  the volume of the primary image. In non-periodic systems, this value
  may not have any significance as the primary image is not related to
  the dynamics of the system. Complex boundary effects, such as walls
  reducing the accessible volume of the system, are not included in
  this calculation. The volume of each particle is calculated from the
  representative interaction which is specified by the
  particle's <a href="/index.php/reference#species">Species tags</a>.
</p>
<p>
  <b>Example output</b>:
</p>
<?php codeblockstart();?>
<Misc>
  <PackingFraction val="0.261799387799154"/>
</Misc>
<?php codeblockend("brush: xml;"); ?>
<p>
  <b>Full Tag, Subtag, and Attribute List</b>:
</p>
<ul>
  <li>
    <b>val</b> <i>(attribute)</i>: The packing fraction of the system.
  </li>
</ul>
<h3>SpeciesCount</h3>
<p>
  This tag contains the number
  of <a href="/index.php/reference#species">Species</a> in the system.
</p>
<p>
  <b>Example output</b>:
</p>
<?php codeblockstart();?>
<Misc>
  <SpeciesCount val="1"/>
</Misc>
<?php codeblockend("brush: xml;"); ?>
<p>
  <b>Full Tag, Subtag, and Attribute List</b>:
</p>
<ul>
  <li>
    <b>val</b> <i>(attribute)</i>: The number of species in the
    system.
  </li>
</ul>
<h3>ParticleCount</h3>
<p>
  This tag contains the number
  of <a href="/index.php/reference#species">Particles</a> in the
  system.
</p>
<p>
  <b>Example output</b>:
</p>
<?php codeblockstart();?>
<Misc>
  <ParticleCount val="1372"/>
</Misc>
<?php codeblockend("brush: xml;"); ?>
<p>
  <b>Full Tag, Subtag, and Attribute List</b>:
</p>
<ul>
  <li>
    <b>val</b> <i>(attribute)</i>: The number of particles in the
    system.
  </li>
</ul>
<h3>SystemMomentum</h3>
<p>
  This tag contains the current and average momentum of all of the
  particles in the system.

  <br/> The averages in this tag are collected exactly (see the
  <a href="/index.php/FAQ#q-how-does-dynamo-collect-exact-timeaverages">FAQ
  on exact averages in DynamO</a>) and so this data is not valid
  when <a href="/index.php/reference#typele">Lees-Edwards boundary
  conditions</a> are applied (or currently in systems with
  gravity, <a href="https://github.com/toastedcrumpets/DynamO/issues/22">see
  issue #22</a>).
</p>
<p>
  <b>Example output</b>:
</p>
<?php codeblockstart();?>
<Misc>
  <SystemMomentum>
    <Current x="-1.02140518265514e-13" y="3.42226247340705e-14" z="-9.39248678832882e-14"/>
    <Average x="-1.02140518265516e-13" y="3.42226247340696e-14" z="-9.39248678832878e-14"/>
  </SystemMomentum>
</Misc>
<?php codeblockend("brush: xml;"); ?>
<p>
  <b>Full Tag, Subtag, and Attribute List</b>:
</p>
<ul>
  <li>
    <b>Current</b> <i>(tag)</i>: The total momentum of the system at
    the moment the output is written out.
    <ul>
      <li>
	<b>x</b>, <b>y</b>, <b>z</b>, <i>(attributes)</i>: The
	components of the current momentum.
      </li>
    </ul>
  </li>
  <li>
    <b>Average</b> <i>(tag)</i>: The time-averaged total momentum of
    the system.
    <ul>
      <li>
	<b>x</b>, <b>y</b>, <b>z</b>, <i>(attributes)</i>: The
	components of the average momentum.
      </li>
    </ul>
  </li>
</ul>
<h3>Temperature</h3>
<p>
  This tag contains the temperature of the particles in the
  system. This includes rotational degrees of freedom (if present). As
  with all temperature values in DynamO, the temperature reported is
  effectively the product, $k_B\,T$ (see
  the <a href="/index.php/FAQ#q-what-are-the-units-of-dynamo">FAQ on
  units</a>).

  <br/> The averages in this tag are collected exactly (see the
  <a href="/index.php/FAQ#q-how-does-dynamo-collect-exact-timeaverages">FAQ
  on exact averages in DynamO</a>) and so this data is not valid
  when <a href="/index.php/reference#typele">Lees-Edwards boundary
  conditions</a> are applied (or currently in systems with
  gravity, <a href="https://github.com/toastedcrumpets/DynamO/issues/22">see
  issue #22</a>).
</p>
<p>
  The temperature is calculated using the standard equipartition
  expression:
  
  \[k_B\,T=\frac{2}{N\,f}\sum_i^N E_i^{kinetic}\]
  
  where $E_i^{kinetic}$ is the kinetic energy of particle $i$
  (including rotational energy) and $f$ is the degrees of freedom of
  the particle. $f$ is automatically set to $f=3$ in systems without
  rotational degrees of freedom and to $f=5$ in systems with
  rotational degrees of freedom.
</p>
<p>
  <b>Example output</b>:
</p>
<?php codeblockstart();?>
<Misc>
  <Temperature Mean="1.00000000000002" MeanSqr="0.999999999999996" Current="1.00000000000001" Min="1.00000000000001" Max="1.00000000000001"/>
</Misc>
<?php codeblockend("brush: xml;"); ?>
<p>
  <b>Full Tag, Subtag, and Attribute List</b>:
</p>
<ul>
  <li>
    <b>Mean</b> <i>(attribute)</i>: The time-averaged temperature,
    $\left\langle k_B\,T\right\rangle$.
  </li>
  <li>
    <b>MeanSqr</b> <i>(attribute)</i>: The time-averaged square of the
    temperature, $\left\langle k_B^2\,T^2\right\rangle$. This can be
    used to work out the standard deviation of the temperature using
    the following formula: \[\sigma = \sqrt{\left\langle
    k_B^2\,T^2\right\rangle - \left\langle k_B\,T\right\rangle^2}\]
  </li>
  <li>
    <b>Current</b> <i>(attribute)</i>: The value of the temperature,
    $k_B\,T$, at the moment the output is written out.
  </li>
  <li>
    <b>Min</b>, <b>Max</b> <i>(attributes)</i>: The minimum and
    maximum values of the temperature during the simulation.
  </li>
</ul>
<h3>UConfigurational</h3>
<p>
  This tag contains the interaction energy per particle. This is equal
  to the excess internal energy (also known as the configurational
  internal energy).

  <br/> The averages in this tag are collected exactly (see the
  <a href="/index.php/FAQ#q-how-does-dynamo-collect-exact-timeaverages">FAQ
  on exact averages in DynamO</a>) and so this data is not valid
  when <a href="/index.php/reference#typele">Lees-Edwards boundary
  conditions</a> are applied (or currently in systems with
  gravity, <a href="https://github.com/toastedcrumpets/DynamO/issues/22">see
  issue #22</a>).
</p>
<p>
  <b>Example output</b>:
</p>
<?php codeblockstart();?>
<Misc>
  <UConfigurational Mean="-7047.30749520661" MeanSqr="49679058.1379387" Current="-7340" Min="-8232" Max="-6912"/>
</Misc>
<?php codeblockend("brush: xml;"); ?>
<p>
  <b>Full Tag, Subtag, and Attribute List</b>:
</p>
<ul>
  <li>
    <b>Mean</b> <i>(attribute)</i>: The time-averaged configurational
    internal energy, $\left\langle U_{conf.}\right\rangle$.
  </li>
  <li>
    <b>MeanSqr</b> <i>(attribute)</i>: The time-averaged square of the
    configurational internal energy, $\left\langle
    U_{conf.}^2\right\rangle$. This can be used to work out the
    standard deviation of the configurational internal energy using
    the following formula: \[\sigma = \sqrt{\left\langle
    U_{conf.}^2\right\rangle - \left\langle
    U_{conf.}\right\rangle^2}\]
  </li>
  <li>
    <b>Current</b> <i>(attribute)</i>: The value of the
    configurational internal energy, $U_{conf.}$, at the moment the
    output is written out.
  </li>
  <li>
    <b>Min</b>, <b>Max</b> <i>(attributes)</i>: The minimum and
    maximum values of the configurational internal energy reached
    during the simulation.
  </li>
</ul>
<h3>ResidualHeatCapacity</h3>
<p>
  This tag is provided for convenience. It contains the excess heat
  capacity, calculated from the fluctuations of the configurational
  internal energy using the following expression:
  
  \[\frac{C_v^{ex.}}{k_B}=\frac{\left\langle U_{conf.}^2\right\rangle
  - \left\langle U_{conf.}\right\rangle^2}{k_B^2\,T^2}\]
  
  To calculate the full heat capacity of the system, the ideal gas
  contribution must be added:

  \[\frac{C_v}{k_B}=\frac{C_v^{ex.}}{k_B} +N\frac{f}{2}\] 

  where $f$ is the degrees of freedom of the particle.
  <br/>
  <b>Note</b>: This expression and the values reported are only valid
  in the canonical (NVT) ensemble.
</p>
<p>
  <b>Example output</b>:
</p>
<?php codeblockstart();?>
<Misc>
  <ResidualHeatCapacity Value="80608.2639343955"/>
</Misc>
<?php codeblockend("brush: xml;"); ?>
<p>
  <b>Full Tag, Subtag, and Attribute List</b>:
</p>
<ul>
  <li>
    <b>Value</b> <i>(attribute)</i>: The calculated excess
    heat capacity $(C_v^{ex.}/k_B)$.
  </li>
</ul>
<h3>Pressure</h3>
<p>
  This tag contains the full pressure tensor for the system, worked
  out using the virial expression:
  
  \[\mathbf{P}=\mathbf{P}^{kinetic}+\mathbf{P}^{interaction}\]
  
  where the kinetic pressure is given by:
  
  \[\mathbf{P}^{kinetic}=\frac{1}{V}\sum_i^N m_i\,\mathbf{v}_i\mathbf{v}_i\]
  
  where $m_i$ is the mass of particle $i$.  Please note that
  $\mathbf{v}_i\mathbf{v}_i$ is a dyadic product which yields a matrix
  result. The contribution to the pressure due to interactions is
  given by:

  \[\mathbf{P}^{interaction}=\frac{1}{V\,t_{sim}}\sum_{ij}^{event} \Delta \mathbf{p}_i\mathbf{r}_{ij}\]

  where $t_{sim}$ is the total simulation time, the summation is over
  each two-particle event
  (<a href="/index.php/reference#interaction">Interaction</a>), $i$
  and $j$ indicate the two particles involved in the event,
  $\Delta\mathbf{p}_i$ is the momentum impulse on particle $i$, and
  $\mathbf{r}_{ij}=\mathbf{r}_{i} - \mathbf{r}_{j}$ is the separation
  vector between the interacting particles. The hydrostatic pressure
  can be computed from the trace of the pressure tensor:
  
  \[p=\mathrm{tr}(\mathbf{P})/3=\left(P_{xx}+P_{yy}+P_{zz}\right)/3\]
</p>
<p>
  <b>Example output</b>:
</p>
<?php codeblockstart();?>
<Misc>
  <Pressure Avg="-1.92667849178502">
    <Tensor>
-1.92776085293681 -0.027284740627551 -0.0330674943624325 
-0.027284740627551 -1.91924243731331 -0.0444242381174982 
-0.0330674943624326 -0.0444242381174982 -1.93303218510494 
    </Tensor>
    <InteractionContribution>
-2.13900845558922 -0.0269634925340249 -0.032459636868961 
-0.0269634925340249 -2.13348059155252 -0.0441115524879792 
-0.032459636868961 -0.0441115524879792 -2.14406792617732 
    </InteractionContribution>
  </Pressure>
</Misc>
<?php codeblockend("brush: xml;"); ?>
<p>
  <b>Full Tag, Subtag, and Attribute List</b>:
</p>
<ul>
  <li>
    <b>Avg</b> <i>(attribute)</i>: This attribute contains the
    hydrostatic pressure, $p$, computed from the trace of the pressure
    tensor.
  </li>
  <li>
    <b>Tensor</b> <i>(tag)</i>: This tag contains the full pressure
    tensor, $\mathbf{P}$, with the components written out as follows:

    \[\begin{align}
    \begin{matrix}
    P_{xx} & P_{xy} & P_{xz}\\
    P_{yx} & P_{yy} & P_{yz}\\
    P_{zx} & P_{zy} & P_{zz}
    \end{matrix}
    \end{align}\]
  </li>
  <li>
    <b>InteractionContribution</b> <i>(tag)</i>: This tag only
    contains the interaction contributions to the pressure tensor
    ($\mathbf{P}^{interaction}$), with the components written out as
    follows:
    
    \[\begin{align}
    \begin{matrix}
    P_{xx}^{interaction} & P_{xy}^{interaction} & P_{xz}^{interaction}\\
    P_{yx}^{interaction} & P_{yy}^{interaction} & P_{yz}^{interaction}\\
    P_{zx}^{interaction} & P_{zy}^{interaction} & P_{zz}^{interaction}
    \end{matrix}
    \end{align}\]
  </li>
</ul>
<h2>IntEnergyHist (Internal Energy Histogram)</h2>
<p>
</p>
<h2>MFT (Mean Free Time)</h2>
<p>
</p>
<h2>RadiusGyration</h2>
<p>
</p>
